package mybatis.bean;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.NAME
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.SURNAME
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    private String surname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.BIRTH_YEAR
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    private Integer birthYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CARD_NO
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.STATUS
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.NAME
     *
     * @return the value of CUSTOMER.NAME
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.NAME
     *
     * @param name the value for CUSTOMER.NAME
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.SURNAME
     *
     * @return the value of CUSTOMER.SURNAME
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.SURNAME
     *
     * @param surname the value for CUSTOMER.SURNAME
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    public void setSurname(String surname) {
        this.surname = surname == null ? null : surname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.BIRTH_YEAR
     *
     * @return the value of CUSTOMER.BIRTH_YEAR
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    public Integer getBirthYear() {
        return birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.BIRTH_YEAR
     *
     * @param birthYear the value for CUSTOMER.BIRTH_YEAR
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    public void setBirthYear(Integer birthYear) {
        this.birthYear = birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CARD_NO
     *
     * @return the value of CUSTOMER.CARD_NO
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CARD_NO
     *
     * @param cardNo the value for CUSTOMER.CARD_NO
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.STATUS
     *
     * @return the value of CUSTOMER.STATUS
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.STATUS
     *
     * @param status the value for CUSTOMER.STATUS
     *
     * @mbggenerated Mon Jan 25 20:09:24 EET 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}